ISSS_Board_Maintenance/Controllers/RutineController.cs
using Aspose.Zip;
using Aspose.Zip.Saving;
using ISSS_Board_Maintenance.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ISSS_Board_Maintenance.Controllers
{
    public class RutineController : Controller
    {
        // GET: Rutine
        public ActionResult Index()
        {
            if (Session["role"] != null)
                try
                {
                    using (var db = new BM_010_ISSSEntities())
                    {
                        List<maintenance_rutineCE> rutinesCE = new List<maintenance_rutineCE>();
                        List<maintenance_rutine> rutines = db.maintenance_rutine.ToList();
                        foreach (maintenance_rutine rutine in rutines)
                        {
                            maintenance_rutineCE rutineCE = new maintenance_rutineCE();
                            rutineCE.ms_id = rutine.ms_id;
                            rutineCE.mr_id = rutine.mr_id;
                            rutineCE.date = rutine.date;
                            rutineCE.employee_user_full_name = rutine.employee_user.name + " " + rutine.employee_user.last_name;
                            rutineCE.hasFiles = db.termography_files.Where(tf => tf.mr_id == rutine.mr_id).ToList().Count == 0 ? false : true;
                            rutinesCE.Add(rutineCE);
                        }
                        return View(rutinesCE);
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            else
                return RedirectToAction("Index", "User");
        }
        public ActionResult IndexEmployee(string id)
        {
            if (Session["role"] != null)
                try
                {
                    using (var db = new BM_010_ISSSEntities())
                    {
                        List<maintenance_rutineCE> rutinesCE = new List<maintenance_rutineCE>();
                        List<maintenance_rutine> rutines = db.maintenance_rutine.Where(mr => mr.ms_id == id).ToList();
                        foreach (maintenance_rutine rutine in rutines)
                        {
                            maintenance_rutineCE rutineCE = new maintenance_rutineCE();
                            rutineCE.ms_id = rutine.ms_id;
                            rutineCE.mr_id = rutine.mr_id;
                            rutineCE.date = rutine.date;
                            rutineCE.employee_user_full_name = rutine.employee_user.name + " " + rutine.employee_user.last_name;
                            rutineCE.hasFiles = db.termography_files.Where(tf => tf.mr_id == rutine.mr_id).ToList().Count == 0 ? false : true;
                            rutinesCE.Add(rutineCE);
                        }
                        return View(rutinesCE);
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            else
                return RedirectToAction("Index", "User");
        }

        // GET: Rutine/Details/5
        public ActionResult Details(int id)
        {
            using (var db = new BM_010_ISSSEntities())
            {
                maintenance_rutineCE rutineCE = new maintenance_rutineCE(db.maintenance_rutine.Find(id));
                maintenance_schedule schedule = db.maintenance_schedule.Find(rutineCE.ms_id);
                rutineCE.description = schedule.type;
                rutineCE.location = schedule.location;
                return View(rutineCE);
            }
        }

        public ActionResult DetailsAsPDF(int id)
        {
            return new ActionAsPdf("Details", new { id = id })
            { FileName = id + "R" + DateTime.Now.ToString("dd") + DateTime.Now.ToString("MM") + DateTime.Now.ToString("yy") + ".pdf" };
        }

        // GET: Rutine/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rutine/Create
        [HttpPost]
        public ActionResult Create(maintenance_rutine rutine)
        {
            using (var db = new BM_010_ISSSEntities())
            {
                maintenance_schedule ms = db.maintenance_schedule.Find(rutine.ms_id);
                rutine.employee_id = Convert.ToInt32(Session["id"]);
                rutine.date = rutine.date == null ? DateTime.Now : rutine.date;
                DateTime dt1 = ((DateTime)rutine.date).AddHours(DateTime.Now.Hour);
                DateTime dt2 = dt1.AddMinutes(DateTime.Now.Minute);
                DateTime dt3 = dt2.AddSeconds(DateTime.Now.Second);
                rutine.date = dt3;
                string tc = rutine.transf_capacity;
                rutine.transf_capacity = string.IsNullOrEmpty(tc) ? "NO APLICA" : tc;
                string pc = rutine.protection_capacity;
                rutine.protection_capacity = string.IsNullOrEmpty(pc) ? "NO APLICA" : pc;
                rutine.general_protection = GetYesNo(rutine.general_protection);
                rutine.initial_termography = GetYesNo(rutine.initial_termography);
                rutine.general_cleaning = GetYesNo(rutine.general_cleaning);
                rutine.cable_managment = GetYesNo(rutine.cable_managment);
                rutine.retighten = GetYesNo(rutine.retighten);
                rutine.rotulation = GetYesNo(rutine.rotulation);
                rutine.final_termography = GetYesNo(rutine.final_termography);
                rutine.cover_placement = GetYesNo(rutine.cover_placement);
                db.maintenance_rutine.Add(rutine);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "User");
        }

        // GET: Rutine/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Rutine/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            using (var db = new BM_010_ISSSEntities())
            {
                db.maintenance_rutine.Remove(db.maintenance_rutine.Find(id));
                db.SaveChanges();
                return RedirectToAction("Index", "User");
            }
        }

        public ActionResult DownloadAttachment(int id)
        {
            using (var db = new BM_010_ISSSEntities())
            {
                List<termography_files> files = db.termography_files.Where(f => f.mr_id == id).ToList();
                using (var ms = new MemoryStream())
                {
                    using (var archive =
                        new ZipArchive(ms, ZipArchiveMode.Create, true))
                    {
                        foreach (termography_files item in files)
                        {
                            var filename = System.IO.Path.GetFileName(item.termography_file);
                            var fileS = System.IO.File.OpenRead(item.termography_file);

                            var fileB = new byte[fileS.Length];
                            fileS.Read(fileB, 0, fileB.Length);

                            var zipEntry = archive.CreateEntry(filename, CompressionLevel.Fastest);
                            using (var zipStream = zipEntry.Open())
                            {
                                zipStream.Write(fileB, 0, fileB.Length);
                            }
                        }
                    }
                    return File(ms.ToArray(),
                        "application/zip",
                        id + "TF" + DateTime.Now.ToString("dd") + DateTime.Now.ToString("MM") + DateTime.Now.ToString("yy") + ".zip");
                }
            }
        }
        public ActionResult UploadTermographyFiles()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UploadTermographyFiles(int id)
        {
            IList<HttpPostedFileBase> files = Request.Files.GetMultiple("termographyFiles");
            if (files.Count > 0)
                using (var db = new BM_010_ISSSEntities())
                {
                    string path = Server.MapPath("~/TF/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    path = Server.MapPath("~/TF/" + id + "/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    foreach (var file in files)
                    {
                        file.SaveAs(path + Path.GetFileName(file.FileName));
                        termography_files tf = new termography_files();
                        tf.mr_id = id;
                        tf.termography_file = path + Path.GetFileName(file.FileName);
                        db.termography_files.Add(tf);
                    }
                    db.SaveChanges();
                }
            return RedirectToAction("Index", "User");
        }
        private string GetYesNo(string verif)
        {
            return string.IsNullOrEmpty(verif) ? "NO" : "SI";
        }
    }
}

ISSS_Board_Maintenance/Controllers/ScheduleController.cs
using ISSS_Board_Maintenance.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISSS_Board_Maintenance.Controllers
{
    public class ScheduleController : Controller
    {
        // GET: Schedule
        public ActionResult Index()
        {
            if (Session["role"] != null)
                try
                {
                    using (var db = new BM_010_ISSSEntities())
                    {
                        var list = db.maintenance_schedule.ToList();
                        List<maintenance_scheduleCE> collection = new List<maintenance_scheduleCE>();
                        foreach (var item in list)
                        {
                            maintenance_scheduleCE obj = new maintenance_scheduleCE();
                            obj.ms_id = item.ms_id;
                            obj.type = item.type;
                            obj.dependency = item.dependency;
                            obj.building = item.building;
                            obj.location = item.location;
                            obj.nomenclature = item.nomenclature;
                            obj.month_scheduled = item.month_scheduled;
                            obj.level = item.level;
                            obj.maintenance_rutine = item.maintenance_rutine;
                            obj.month_scheduled_name = new DateTime(2000, item.month_scheduled, 1)
                                .ToString("MMMM", CultureInfo.CreateSpecificCulture("es"));
                            collection.Add(obj);
                        }
                        return View(collection);
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            else
                return RedirectToAction("Index", "User");
        }

        public ActionResult IndexEmployee(int id)
        {
            if (Session["role"] != null)
                try
                {
                    using (var db = new BM_010_ISSSEntities())
                    {
                        var list = db.maintenance_schedule
                            .ToList()
                            .Where(ms => ms.month_scheduled == id 
                            && ms.dependency_id == Convert.ToInt32(Session["dependency_id"]));
                        List<maintenance_scheduleCE> collection = new List<maintenance_scheduleCE>();
                        foreach (var item in list)
                        {
                            maintenance_scheduleCE obj = new maintenance_scheduleCE();
                            obj.ms_id = item.ms_id;
                            obj.type = item.type;
                            obj.dependency = item.dependency;
                            obj.building = item.building;
                            obj.location = item.location;
                            obj.nomenclature = item.nomenclature;
                            obj.month_scheduled = item.month_scheduled;
                            obj.level = item.level;
                            obj.maintenance_rutine = item.maintenance_rutine;
                            obj.month_scheduled_name = new DateTime(2000, item.month_scheduled, 1)
                                .ToString("MMMM", CultureInfo.CreateSpecificCulture("es"));
                            collection.Add(obj);
                        }
                        return View(collection);
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            else
                return RedirectToAction("Index", "User");
        }

        // GET: Schedule/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Schedule/Create
        [HttpPost]
        public ActionResult Create(maintenance_schedule schedule)
        {
            if (string.IsNullOrWhiteSpace(schedule.building) || string.IsNullOrWhiteSpace(schedule.level)
                || string.IsNullOrWhiteSpace(schedule.location) || string.IsNullOrWhiteSpace(schedule.nomenclature)
                || string.IsNullOrWhiteSpace(schedule.type) || string.IsNullOrWhiteSpace(schedule.ms_id))
                TempData["noFullDataSchedule"] = "noFullDataSchedule";
            else
            {
                using (var db = new BM_010_ISSSEntities())
                {
                    if (db.maintenance_schedule.Find(schedule.ms_id) == null)
                    {
                        db.maintenance_schedule.Add(schedule);
                        db.SaveChanges();
                    }
                    else
                        TempData["noValidCode"] = "Codigo existente";
                }
            }
            return RedirectToAction("Index", "User");
        }

        // GET: Schedule/Edit/5
        public ActionResult Edit()
        {
            return View();
        }

        // POST: Schedule/Edit/5
        [HttpPost]
        public ActionResult Edit(maintenance_schedule schedule)
        {
            if (string.IsNullOrWhiteSpace(schedule.building) || string.IsNullOrWhiteSpace(schedule.level)
                || string.IsNullOrWhiteSpace(schedule.location) || string.IsNullOrWhiteSpace(schedule.nomenclature)
                || string.IsNullOrWhiteSpace(schedule.type))
                TempData["noFullDataScheduleEdit"] = schedule.ms_id;
            else
            {
                using (var db = new BM_010_ISSSEntities())
                {
                    maintenance_schedule sc = db.maintenance_schedule.Find(schedule.ms_id);
                    sc.type = schedule.type;
                    sc.dependency_id = schedule.dependency_id;
                    sc.building = schedule.building;
                    sc.level = schedule.level;
                    sc.location = schedule.location;
                    sc.nomenclature = schedule.nomenclature;
                    sc.month_scheduled = schedule.month_scheduled;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index", "User");
        }

        // GET: Schedule/Delete/5
        public ActionResult Delete(string id)
        {
            using (var db = new BM_010_ISSSEntities())
            {
                db.maintenance_schedule.Remove(db.maintenance_schedule.Find(id));
                db.SaveChanges();
                return RedirectToAction("Index", "User");
            }
        }
    }
}

ISSS_Board_Maintenance/Views/User/Edit.cshtml
@model ISSS_Board_Maintenance.Models.employee_userCE

@using (Html.BeginForm("Edit", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin-right:-50px">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                <input class="editUser" id="employee_id" name="employee_id" style="display:none;">
            </div>
        </div>

        <div class="form-group">
            Nombre de usuario
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control editUser" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Nombres<br />
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control editUser" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Apellidos<br />
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control editUser" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Contraseña
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control editUser", @type = "password" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Firma<br />
            <div class="col-md-10">
                @Html.Editor("signatureData", new
                     {
                         htmlAttributes = new
                         {
                            @id = "signatureData",
                            @name = "signatureData",
                            @class = "form-control",
                            @type = "file",
                            @style = "height: 40px",
                            @onchange = "fileCheck(this);",
                            @accept = "image/*"
                         }
                     })
                @Html.ValidationMessageFor(model => model.signature, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Dependencia
            <div class="col-md-10">
                <select id="dependency_id" name="dependency_id" class="form-control editUser" style="height:40px;">
                </select>
                @Html.ValidationMessageFor(model => model.dependency_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <input type="submit" value="Editar" class="btn btn-info btn-lg" />
            </div>
        </div>
    </div>
}

ISSS_Board_Maintenance/Views/User/Home.cshtml
@{ ViewBag.Title = "Técnico"; }

@section Styles{
    @Styles.Render("https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900")
    @Styles.Render("~/fonts/font-awesome-4.7.0/css/font-awesome.min.css")
    @Styles.Render("~/fonts/iconic/css/material-design-iconic-font.min.css")
    @Styles.Render("~/Content/nav_style.css")
    @Styles.Render("~/Content/bootstrap.min.css")
}
<div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar" class="active fixed-left" style="position: fixed; height: 100%; z-index: 100; ">
        <div class="custom-menu">
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
                <i class="fa fa-bars"></i>
                <span class="sr-only">Toggle Menu</span>
            </button>
        </div>
        <div class="p-4">
            <h1><a class="logo">Planificación</a></h1>
            <div style="overflow:auto">
                <ul class="list-unstyled components mb-5" id="monthOptions" style="cursor:pointer">
                    <li id="year-1" class="active months">
                        <a>Enero</a>
                    </li>
                    <li id="year-2" class="months">
                        <a>Febrero</a>
                    </li>
                    <li id="year-3" class="months">
                        <a>Marzo</a>
                    </li>
                    <li id="year-4" class="months">
                        <a>Abril</a>
                    </li>
                    <li id="year-5" class="months">
                        <a>Mayo</a>
                    </li>
                    <li id="year-6" class="months">
                        <a>Junio</a>
                    </li>
                    <li id="year-7" class="months">
                        <a>Julio</a>
                    </li>
                    <li id="year-8" class="months">
                        <a>Agosto</a>
                    </li>
                    <li id="year-9" class="months">
                        <a>Septiembre</a>
                    </li>
                    <li id="year-10" class="months">
                        <a>Octubre</a>
                    </li>
                    <li id="year-11" class="months">
                        <a>Noviembre</a>
                    </li>
                    <li id="year-12" class="months">
                        <a>Diciembre</a>
                    </li>
                </ul>
            </div>
            <div class="footer">
                <ul class="list-unstyled components mb-5">
                    <li style="position:relative; bottom:0px">
                        <a style="cursor:pointer" id="logOutBtn"><span class="fa fa-sign-out mr-3"></span> Cerrar Sesión</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content  -->

    <div id="content" class="p-4 p-md-5 pt-5" style="margin-left:50px">
        <h2 class="mb-4">
            Gestión de mantenimiento eléctrico<br />
            @Session["dependency_name"].ToString()
        </h2>

        <div class="modal fade" id="uploadFilesModal" role="dialog">
            <div class="modal-dialog" style="max-width:25% !important;">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Agregar archivos termográficos</h4>
                        <button type="button" class="close" data-dismiss="modal" style="margin-top:unset;">&times;</button>
                    </div>
                    <div id="modal-body-content" class="modal-body" style="margin-left: 35px; margin-right: 35px;">
                    </div>
                </div>
            </div>
        </div>

        <div id="contentDiv">
            @{ Html.RenderAction("IndexEmployee", "Schedule", new { id = 1 }); }
        </div>

        <div id="rutineDiv">
        </div>

        <div id="createRutineDiv" style="display:none;">
            @{ Html.RenderAction("Create", "Rutine"); }
        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/jquery-3.4.1.min.js")
    @Scripts.Render("~/Scripts/nav_main.js")
    @Scripts.Render("~/Scripts/Highcharts-4.0.1/js/highcharts.js")
    @Scripts.Render("https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js")
    <script>
        var getUrl = window.location;
        var baseUrl = getUrl.protocol + "//" + getUrl.host + "/";
        $(document).ready(function () {
            $("#addTF").click(function () {
                window.location.href = "@Url.Action("UploadTermographyFiles", "Rutine")";
            });
            $("#logOutBtn").click(function () {
                window.location.href = "@Url.Action("logOut", "User")";
            });
            $(".months").click(function () {
                if (!$(this).hasClass("active")) {
                    $("#monthOptions li").removeClass("active");
                    $(this).addClass("active");
                    var id = $(this).attr("id").substring(5);
                    $("#contentDiv").empty();
                    $("#createRutineDiv").hide();
                    $("#rutineDiv").hide();
                    $("#contentDiv").show();
                    $.ajax({
                        type: "GET",
                        url: baseUrl + "Schedule/IndexEmployee/" + id,
                        dataType: "HTML",
                        success: function (response) {
                            $("#contentDiv").html(response);
                        }
                    });
                }
            });
            $("#FullNameCreateRutine").text('@Session["fullname"]');
            $("#SignatureCreateRutine").attr('src','@Url.Action("GetSignature", "User", new { id = Convert.ToInt32(Session["id"].ToString()) })');
    });
    </script>
}

ISSS_Board_Maintenance/Views/User/Index.cshtml
@{
    ViewBag.Title = "Iniciar Sesión";
}

@section Styles
{
    @Styles.Render("~/Content/login_main.css")
    @Styles.Render("~/Content/login_util.css")
}
<div class="container-login100" style="background-image: url('../../images/isss_bg_1.png')">
    <div class="wrap-login100 p-l-75 p-r-55 p-t-55 p-b-55">
        <table>
            <tr>
                <th>
                    @{ Html.RenderAction("Login", "User"); }
                </th>
                <th>
                    @{ Html.RenderAction("SignIn", "User"); }
                </th>
            </tr>
        </table>
    </div>
</div>
@{
    if (null != TempData["noFullData"] || null != TempData["maxSizeReached"] || null != TempData["userFound"])
    {
        <script>
            $("#loginSection").hide();
            $("#signinSection").show();
        </script>
    }
}

ISSS_Board_Maintenance/Views/User/List.cshtml
@model IEnumerable<ISSS_Board_Maintenance.Models.employee_userCE>
<table class="table">
    <tr>
        <th>
            Nombres
        </th>
        <th>
            Apellidos
        </th>
        <th>
            Nombre de usuario
        </th>
        <th>
            Firma
        </th>
        <th>
            Dependencia
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="background-color:@((bool)item.verification ? "#90EE90" : "#FFCCCB")">
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.last_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                <img src="@Url.Action("GetSignature", "User", new { id = item.employee_id })" height="75" width="225">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dependecy_name)
            </td>
            <td>
                @Html.ActionLink("Dar de alta", "SuscribeUser", new { id = item.employee_id }) |
                @Html.ActionLink("Dar de baja", "UnsuscribeUser", new { id = item.employee_id }) |
                <a id="EU-@item.employee_id" class="editUserF" style="cursor:pointer; color:darkblue;">
                    Editar
                </a>
            </td>
        </tr>
    }

</table>

@section Scripts{
    <script>
        $(document).ready(function () {
            var getUrl = window.location;
            var baseUrl = getUrl.protocol + "//" + getUrl.host + "/";
            $(".login100-form-title").hide();
            $(".editUserF").click(function () {
                var id = $(this).attr("id").substring(3);
                $.ajax({
                    type: "GET",
                    url: baseUrl + "api/UserAPI/" + id,
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (response) {
                        $(".editUser#employee_id").val(response.employee_id);
                        $(".editUser#username").val(response.username);
                        $(".editUser#name").val(response.name);
                        $(".editUser#last_name").val(response.last_name);
                        $(".editUser#password").val(response.password);
                        $(".editUser#dependency_id").val(response.dependency_id);
                    }
                });
                $("#editUserModal").modal('show');
            });
        });
    </script>
}